name: impe
version: 0.1.0.0
github: "githubuser/impe"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/githubuser/impe#readme>

dependencies:
  - base >= 4.7 && < 5
  - polysemy
  - polysemy-plugin
  - mtl
  - lens
  - containers
  - parsec
  - optparse-applicative
  - gitrev

library:
  source-dirs: src
  default-extensions:
    - GADTs
    - LambdaCase
    - BlockArguments
    - TemplateHaskell
    - RankNTypes
    - FlexibleInstances
    - MultiParamTypeClasses
    - FlexibleContexts
    - UndecidableInstances
    - DataKinds
    - TypeOperators
    - TypeFamilies
    - ApplicativeDo
  ghc-options:
    - -Wall
    - -Wno-missing-signatures
    - -Wno-unused-do-bind
    - -fplugin=Polysemy.Plugin

executables:
  impe-exe:
    main: Main.hs
    source-dirs: app
    default-extensions:
      - GADTs
      - LambdaCase
      - BlockArguments
      - TemplateHaskell
      - RankNTypes
      - FlexibleInstances
      - MultiParamTypeClasses
      - FlexibleContexts
      - UndecidableInstances
      - DataKinds
      - TypeFamilies
      - TypeOperators
      - ApplicativeDo
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      # - -Wall
      - -fplugin=Polysemy.Plugin
    dependencies:
      - impe

tests:
  impe-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
      - GADTs
      - LambdaCase
      - BlockArguments
      - TemplateHaskell
      - RankNTypes
      - FlexibleInstances
      - MultiParamTypeClasses
      - FlexibleContexts
      - UndecidableInstances
      - DataKinds
      - TypeFamilies
      - ApplicativeDo
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -fplugin=Polysemy.Plugin
    dependencies:
      - impe
